apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helved-performance
  namespace: helved
spec:
  ingresses: [ https://helved-performance.intern.dev.nav.no ]
  liveness:
    path: /health
  readiness:
    path: /health
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 20m
      memory: 24Mi
    limits:
      memory: 128Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: utsjekk
