apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helved-performance
  namespace: helved
spec:
  ingresses:
    - https://helved-performance.intern.dev.nav.no
  liveness:
    path: /health
  readiness:
    path: /health
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 150m
      memory: 32Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: utsjekk
        - application: abetal
